# Generated by Django 3.0.7 on 2021-03-19 12:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('customer_lastname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('customer_adress', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=20, region=None, verbose_name='Нормализованный номер владельца')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.FoodCart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.Product')),
            ],
        ),
    ]
