# Generated by Django 3.0.7 on 2021-03-26 16:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20210325_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=20, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
