# Generated by Django 3.0.7 on 2021-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20210401_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
