# Generated by Django 3.0.7 on 2021-04-13 13:31

from django.db import migrations

def get_order_prices(apps, schema_editor):
    Entry = apps.get_model('foodcartapp', 'Entry')
    for entry in Entry.objects.prefetch_related('product').iterator():
        if entry.price is None:
            entry.price = entry.product.price
            entry.save(update_fields=['price'])

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_entry_price'),
    ]

    operations = [
    migrations.RunPython(get_order_prices)
    ]
    