# Generated by Django 3.0.7 on 2021-04-22 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20210413_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='status',
            field=models.CharField(blank=True, choices=[('Recieved', 'Доставлен'), ('In progress', 'В обработке')], max_length=30, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
