# Generated by Django 3.0.7 on 2021-04-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20210422_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
