# Generated by Django 3.0.7 on 2021-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20210423_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Наличными'), ('By card', 'Картой')], max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
