# Generated by Django 3.0.7 on 2021-04-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_foodcart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_order', to='foodcartapp.Restaurant', verbose_name='ресторан'),
        ),
    ]
