# Generated by Django 3.0.7 on 2021-10-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_foodcart_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='foodcartapp.Restaurant', verbose_name='ресторан'),
        ),
    ]
