# Generated by Django 3.0.7 on 2021-10-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20211005_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='called_at',
            field=models.DateTimeField(blank=True, verbose_name='Звонок совершен'),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='delivered_at',
            field=models.DateTimeField(blank=True, verbose_name='Заказ доставлен'),
        ),
    ]
