# Generated by Django 3.0.7 on 2021-10-05 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20211005_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Звонок совершен'),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Заказ доставлен'),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Наличными'), ('By card', 'Картой')], db_index=True, max_length=30, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='registrated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Заказ зарегестрирован'),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='status',
            field=models.CharField(blank=True, choices=[('Recieved', 'Доставлен'), ('In progress', 'В обработке')], db_index=True, max_length=30, verbose_name='Статус заказа'),
        ),
    ]
