# Generated by Django 3.0.7 on 2021-10-05 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20211005_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='foodcartapp.FoodCart'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entries', to='foodcartapp.Product'),
        ),
    ]
