# Generated by Django 3.0.7 on 2021-10-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20211005_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='foodcartapp.FoodCart'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='foodcartapp.Product'),
        ),
    ]
