# Generated by Django 3.0.7 on 2021-10-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20211006_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.Restaurant', verbose_name='ресторан'),
        ),
    ]
