# Generated by Django 3.0.7 on 2021-11-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20211006_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='status',
            field=models.CharField(blank=True, choices=[('Unprocessed', 'Не обработан'), ('Recieved', 'Доставлен'), ('In progress', 'В обработке')], db_index=True, default='Unprocessed', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
