# Generated by Django 3.0.7 on 2021-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20211123_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Не обработан'), ('Recieved', 'Доставлен'), ('In progress', 'В обработке')], db_index=True, default='Unprocessed', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
