# Generated by Django 3.0.7 on 2021-11-26 11:40

from django.db import migrations

def update_foodcart_status(apps, schema_editor):
    FoodCart = apps.get_model('foodcartapp', 'FoodCart')
    for order in FoodCart.objects.filter(status=''):
        order.status = 'Unprocessed'
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20211126_1423'),
    ]

    operations = [
        migrations.RunPython(update_foodcart_status),
    ]
